# Generated by Django 3.2.6 on 2021-08-31 11:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.FileField(upload_to='pdfs', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
