# Generated by Django 3.2.6 on 2021-08-31 12:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0002_alter_document_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='data',
            field=models.FileField(upload_to='pdf_files', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
