# Generated by Django 3.2.6 on 2021-08-31 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manage', '0003_alter_document_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='data',
            new_name='pdf',
        ),
    ]
