# Generated by Django 3.2.6 on 2021-08-23 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bgt', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='expense',
            name='Bills',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='Food',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='Health',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='Investments',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='Personal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='expense',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='eduction',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='gifts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='expense',
            name='travel',
            field=models.IntegerField(default=0),
        ),
    ]
