# Generated by Django 3.2.6 on 2021-08-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='award',
            field=models.ManyToManyField(to='reward.Award'),
        ),
    ]
