# Generated by Django 3.2.6 on 2021-08-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='link',
            field=models.URLField(default='http://www.foo.com'),
        ),
    ]
