# Generated by Django 3.2.6 on 2021-08-15 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_table_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='NULL', max_length=100),
        ),
    ]
