# Generated by Django 3.2.6 on 2021-08-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel', models.IntegerField()),
                ('eduction', models.IntegerField()),
                ('gifts', models.IntegerField()),
            ],
        ),
    ]
