# Generated by Django 3.2.6 on 2021-08-23 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210823_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 23, 12, 38, 24, 786150)),
        ),
    ]
