# Generated by Django 3.2.6 on 2021-09-08 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Birthday')),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('joining_date', models.DateTimeField(blank=True, null=True, verbose_name='Joining Date')),
                ('address', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
